title: "MATH 60630A - Machine Learning II : Deep Learning"
description: HEC Montr√©al
google_analytics:
theme: jekyll-theme-cayman


url: "https://andyjzhao.github.io"
baseurl: "/Math60630A_2024A"
#baseurl: "/"